[[oidc_providers]]
#id = "provider-id"
#name = "Provider Name"
#authority = "Authority URL"
#client_id = ""
#scopes = [ "openid", "profile", "email" ]
#icon = "URL of icon"

[s3]
endpoint = ""
access_key = ""
secret_access_key = ""
bucket_name = ""
public_url = "https://cdn.example.com"